### ISSUE TITLE
FileNotFoundError: comodoecccertificationauthority-ev-comodoca-com-chain.pem

### ISSUE THREAD

**Issue by nmweizi** [saleemrashid/badecparams#3]
python3 badecparams.py
Traceback (most recent call last):
  File "badecparams.py", line 371, in <module>
    main()
  File "badecparams.py", line 325, in main
    "comodoecccertificationauthority-ev-comodoca-com-chain.pem"
  File "badecparams.py", line 18, in cacert_certificates
    os.path.join(os.path.dirname(os.path.abspath(__file__)), filename), "rb"
FileNotFoundError: [Errno 2] No such file or directory: '/home/aa/cve/badecparams/comodoecccertificationauthority-ev-comodoca-com-chain.pem'

**Comment by saleemrashid** [comment]
Fixed in 5cc215b
